import 'dart:convert';

// ─────────────────────────────────────────────────────────────────────────────
// QrService
// ─────────────────────────────────────────────────────────────────────────────

/// Encodes and decodes the JSON payload embedded inside IPTV playlist QR codes.
///
/// QR payload format (JSON):
/// ```json
/// { "url": "http://...", "name": "Mi IPTV" }
/// ```
///
/// The decoder also accepts a raw URL string (not JSON) as a fallback so that
/// plain-URL QR codes generated by third-party tools still work.
class QrService {
  const QrService._();
  static const instance = QrService._();

  // ── Encode ─────────────────────────────────────────────────────────────────

  /// Returns a JSON string suitable for embedding in a QR code.
  String encode(String url, String name) =>
      jsonEncode({'url': url.trim(), 'name': name.trim()});

  // ── Decode ─────────────────────────────────────────────────────────────────

  /// Parses [raw] (the string read from a QR code) into url + name.
  ///
  /// Returns `null` when [raw] cannot be interpreted as a playlist descriptor.
  ({String url, String name})? decode(String raw) {
    final trimmed = raw.trim();

    // ── 1. Try JSON ──────────────────────────────────────────────────────────
    try {
      final dynamic parsed = jsonDecode(trimmed);
      if (parsed is Map<String, dynamic>) {
        final url = (parsed['url'] as String?)?.trim() ?? '';
        if (url.isEmpty) return null;
        final name = (parsed['name'] as String?)?.trim() ?? '';
        return (url: url, name: name);
      }
    } catch (_) {
      // Not valid JSON — fall through.
    }

    // ── 2. Fallback: treat as raw URL ────────────────────────────────────────
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
      return (url: trimmed, name: '');
    }

    return null; // Unrecognised format.
  }
}
